package com.duke.db.beans;
// Generated 18-Jan-2017 5:19:36 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CountryMaster generated by hbm2java
 */
@Entity
@Table(name = "CountryMaster", catalog = "invoicedb")
public class CountryMaster implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Business> businesses = new HashSet<Business>(0);

	public CountryMaster() {
	}

	public CountryMaster(String name) {
		this.name = name;
	}

	public CountryMaster(String name, Set<Business> businesses) {
		this.name = name;
		this.businesses = businesses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countryMaster")
	public Set<Business> getBusinesses() {
		return this.businesses;
	}

	public void setBusinesses(Set<Business> businesses) {
		this.businesses = businesses;
	}

}
