package com.duke.db.beans;
// Generated 18-Jan-2017 5:19:36 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name = "Document", catalog = "invoicedb")
public class Document implements java.io.Serializable {

	private Integer id;
	private Business business;
	private String contractTerm;
	private String footerNote;

	public Document() {
	}

	public Document(Business business) {
		this.business = business;
	}

	public Document(Business business, String contractTerm, String footerNote) {
		this.business = business;
		this.contractTerm = contractTerm;
		this.footerNote = footerNote;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BusinessID", nullable = false)
	public Business getBusiness() {
		return this.business;
	}

	public void setBusiness(Business business) {
		this.business = business;
	}

	@Column(name = "ContractTerm")
	@Lob
	public String getContractTerm() {
		return this.contractTerm;
	}

	public void setContractTerm(String contractTerm) {
		this.contractTerm = contractTerm;
	}

	@Column(name = "FooterNote")
	@Lob
	public String getFooterNote() {
		return this.footerNote;
	}

	public void setFooterNote(String footerNote) {
		this.footerNote = footerNote;
	}

}
