package com.duke.db.beans;
// Generated 18-Jan-2017 5:19:36 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmailMessage generated by hbm2java
 */
@Entity
@Table(name = "EmailMessage", catalog = "invoicedb")
public class EmailMessage implements java.io.Serializable {

	private Integer id;
	private Business business;
	private String invoiceMessage;
	private String esitmateMessage;

	public EmailMessage() {
	}

	public EmailMessage(Business business) {
		this.business = business;
	}

	public EmailMessage(Business business, String invoiceMessage, String esitmateMessage) {
		this.business = business;
		this.invoiceMessage = invoiceMessage;
		this.esitmateMessage = esitmateMessage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BusinessID", nullable = false)
	public Business getBusiness() {
		return this.business;
	}

	public void setBusiness(Business business) {
		this.business = business;
	}

	@Column(name = "InvoiceMessage")
	@Lob
	public String getInvoiceMessage() {
		return this.invoiceMessage;
	}

	public void setInvoiceMessage(String invoiceMessage) {
		this.invoiceMessage = invoiceMessage;
	}

	@Column(name = "EsitmateMEssage")
	@Lob
	public String getEsitmateMessage() {
		return this.esitmateMessage;
	}

	public void setEsitmateMessage(String esitmateMessage) {
		this.esitmateMessage = esitmateMessage;
	}

}
