package com.duke.db.beans;
// Generated 18-Jan-2017 5:19:36 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LineItem generated by hbm2java
 */
@Entity
@Table(name = "LineItem", catalog = "invoicedb")
public class LineItem implements java.io.Serializable {

	private Integer id;
	private Business business;
	private String description;
	private BigDecimal rate;
	private Set<Invoice> invoices = new HashSet<Invoice>(0);
	private Set<Taxes> taxeses = new HashSet<Taxes>(0);

	public LineItem() {
	}

	public LineItem(Business business, BigDecimal rate) {
		this.business = business;
		this.rate = rate;
	}

	public LineItem(Business business, String description, BigDecimal rate, Set<Invoice> invoices, Set<Taxes> taxeses) {
		this.business = business;
		this.description = description;
		this.rate = rate;
		this.invoices = invoices;
		this.taxeses = taxeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BusinessID", nullable = false)
	public Business getBusiness() {
		return this.business;
	}

	public void setBusiness(Business business) {
		this.business = business;
	}

	@Column(name = "Description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Rate", nullable = false)
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "LineItem_Invoice", catalog = "invoicedb", joinColumns = {
			@JoinColumn(name = "LineItemID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "InvoiceID", nullable = false, updatable = false) })
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Taxes_LineItem", catalog = "invoicedb", joinColumns = {
			@JoinColumn(name = "LineItemID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "TaxesID", nullable = false, updatable = false) })
	public Set<Taxes> getTaxeses() {
		return this.taxeses;
	}

	public void setTaxeses(Set<Taxes> taxeses) {
		this.taxeses = taxeses;
	}

}
