package com.duke.db.beans;
// Generated 18-Jan-2017 5:19:36 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subscription generated by hbm2java
 */
@Entity
@Table(name = "SUBSCRIPTION", catalog = "invoicedb")
public class Subscription implements java.io.Serializable {

	private Integer id;
	private Date joinDate;
	private Date closeDate;
	private Set<Business> businesses = new HashSet<Business>(0);
	private Set<Customer> customers = new HashSet<Customer>(0);

	public Subscription() {
	}

	public Subscription(Date joinDate, Date closeDate, Set<Business> businesses, Set<Customer> customers) {
		this.joinDate = joinDate;
		this.closeDate = closeDate;
		this.businesses = businesses;
		this.customers = customers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JoinDate", length = 19)
	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CloseDate", length = 19)
	public Date getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscription")
	public Set<Business> getBusinesses() {
		return this.businesses;
	}

	public void setBusinesses(Set<Business> businesses) {
		this.businesses = businesses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscription")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
